//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logsale
    {
        public int idx { get; set; }
        public string username { get; set; }
        public byte[] loginName { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> pro_amount { get; set; }
        public Nullable<decimal> pro_price { get; set; }
    }
}
