//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public int idx { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string loginName { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> dateCreateLogin { get; set; }
        public Nullable<int> typeUser { get; set; }
    }
}
